### PR TITLE
Some ideas which might be good 

### PR DESCRIPTION
**Pull request by wucke13**
~~1. removed license header, due to redundancy~~
~~2. linted/indented according to arduino standards (CTRL+T in Arduino IDE)~~
~~3. put initialise lcd call into setup() function~~
~~4. removed suspicious while loop in setup() function~~
~~5. changed delay based random toggle prevention to while based~~
~~6. changed start_time > 0 to start_time != 0, because start_time cannot be less than 0, so its functional equivalent but more clear what shall be the condition~~
7. added improved version of an interrupt based driver

### CODE REVIEW

**Comment by shibumi** [comment]
removing the license header is a bad idea. I know that most people think one LICENSE file is enough inside of the repository, but you should at least provide a small header in each file. Here are some advantages of this:

1. you will have LICENSE information in non-stripped-binaries.
2. It connects the source file explicitly with your LICENSE. 
3. Some LICENSES even demand that you put a header in all source files. Not sure about MIT in this case in particular.

**Comment by c-s-1** [comment]
I agree with @shibumi on the license header. I'll leave it as it is. Thanks for the hint with the lining/indenting, I'll change that. The while loop in the setup is needed because otherwise the welcome screen immediately disappears (if I don't misunderstand what you meant). The while based random toggle prevention is a great idea.

**Comment by c-s-1** [comment]
Placing the initialisation of the LCD into setup() doesn't work because then "lcd" isn't known outside the scope of setup() (forgot to write that earlier).

**Comment by wucke13** [comment]
Regarding the LCD, would it be an option to declare it globally but to initialize inside of `setup()`? 
Are you interested in the interrupt driven delta_t driver? 
Shall I redo my PR, or will you do the pending changes on your own? 

PS:
@shibumi 
I highly doubt that having license information in the binary on an MCU is of interest, as it wastes a lot of space. Furthermore the license information hopefully will be stripped on generation of hex code. Number 1 and 3 make a good point anyway.

**Comment by c-s-1** [comment]
I put your suggestions in a dev branch as far as I could work them into the code.  In the dev branch there's also a fix for a bug that I still had when resetting the content of the LCD.

According to the Arduino Reference, comments are stripped away before compiling: [Arduino Reference: Single Line Comments](https://www.arduino.cc/reference/en/language/structure/further-syntax/singlelinecomment/)
So that shouldn't be an issue (the same is true for block comments).

Regarding the delta_t driver: I'm interested how it works. I'd like to evaluate it from your fork as soon as you think it works. BTW: It's probably a good idea to rebase the sketch on the one I have in the dev branch.

**Comment by wucke13** [comment]
I wrote a little usage in the header file of the driver. It should be as easy as 
* `delta_t_arm()`
* wait for the two interrupts to occur
* `delta_t_get()` to retrieve the measured time delta.

**Pull request closed without merging**
